'use strict';
let catalogue;let filter='all';const cards=document.querySelector('#cards');const dialog=document.querySelector('#detail');
function el(tag,text,cls){const x=document.createElement(tag);if(text!==undefined)x.textContent=text;if(cls)x.className=cls;return x;}
const glyphs={'signalkeepers':'⌁','signalkeepers-models':'⚒','trail-ledger':'↗','hearthside':'♨','fieldcraft':'◇'};
async function verifiedDownload(event,p){
  event.preventDefault();const status=document.querySelector('#status');status.textContent='Checking '+p.filename+'…';
  try{if(!crypto.subtle)throw Error('Checksum verification requires HTTPS or localhost.');
    const response=await fetch(p.url);if(!response.ok)throw Error('Download unavailable.');
    const data=await response.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',data)),n=>n.toString(16).padStart(2,'0')).join('');
    if(hash!==p.sha256)throw Error('Checksum mismatch. Download stopped.');
    const url=URL.createObjectURL(new Blob([data],{type:'application/zip'}));const a=el('a');a.href=url;a.download=p.filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);
    status.textContent='Checksum matched the catalogue. '+p.filename+' is ready.';
  }catch(error){status.textContent=error.message;}
}
function download(p){const a=el('a','Download ↓');a.href=p.url;a.download=p.filename;a.addEventListener('click',e=>verifiedDownload(e,p));return a;}
function render(){cards.replaceChildren();const q=document.querySelector('#search').value.toLowerCase();const packs=catalogue.packs.filter(p=>(filter==='all'||p.kind===filter)&&(p.name+' '+p.description).toLowerCase().includes(q));document.querySelector('#count').textContent=String(packs.length).padStart(2,'0');for(const p of packs){const card=el('article',undefined,'card');const art=el('div',undefined,'card-art');art.style.setProperty('--accent',p.accent);art.setAttribute('aria-hidden','true');art.append(el('span',glyphs[p.id],'glyph'),el('span',p.kind==='resourcepack'?'MODEL COLLECTION':'FIELD EXPERIMENT','art-label'),el('span',String(catalogue.packs.indexOf(p)+1).padStart(2,'0'),'pack-no'));const body=el('div',undefined,'card-body');const category=el('div',undefined,'card-category');category.append(el('span',p.category),el('span','ALPHA / '+p.version));body.append(category,el('h3',p.name),el('p',p.tagline));const features=el('ul',undefined,'features');p.features.forEach(f=>features.append(el('li',f)));body.append(features);const actions=el('div',undefined,'card-actions');const details=el('button','Field guide ↗');details.addEventListener('click',()=>showDetail(p));actions.append(download(p),details);body.append(actions,el('div',`JAVA 1.21.1 · ${(p.bytes/1024).toFixed(1)} KB · FREE`,'card-foot'));card.append(art,body);cards.append(card);}if(!packs.length)cards.append(el('p','No packs match. Try another search or filter.'));}
function showDetail(p){const content=document.querySelector('#detail-content');content.replaceChildren(el('p',p.category.toUpperCase(),'eyebrow'),el('h2',p.name),el('p',p.description));for(const [title,value] of [['Start here',p.entrypoint],['Compatibility',p.conflicts],['Validation',p.testStatus],['Dependencies',p.dependencies.length?p.dependencies.join(', '):'None'],['Remove safely',p.uninstall]])content.append(el('h3',title),el(title==='Start here'||title==='Remove safely'?'code':'p',value));content.append(el('h3','SHA-256 checksum'));const row=el('div',undefined,'checksum');const copy=el('button','Copy');copy.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(p.sha256);copy.textContent='Copied';}catch{copy.textContent='Select to copy';}});row.append(el('code',p.sha256),copy);content.append(row,el('p','Integrity relative to this catalogue; publisher authentication requires verifying a release attestation.'),download(p));dialog.showModal();}
document.querySelector('#close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{const active=x===b;x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active));});if(catalogue)render();}));document.querySelector('#search').addEventListener('input',()=>{if(catalogue)render();});
fetch('catalog.json').then(r=>{if(!r.ok)throw Error('Catalogue unavailable');return r.json();}).then(c=>{catalogue=c;const bundle=document.querySelector('#bundle');bundle.href=c.bundle.url;bundle.download=c.bundle.filename;bundle.hidden=false;bundle.addEventListener('click',e=>verifiedDownload(e,c.bundle));render();}).catch(()=>{cards.replaceChildren(el('p','The catalogue could not load. Please refresh or visit the source repository.'));document.querySelector('#status').textContent='If previewing locally, run the build and serve the generated site folder over HTTP.';});
